import type { Metadata } from "next";

import "./globals.css";
import { PT_Serif } from "next/font/google";
import Navbar from "@/components/ui/NavBar";
import Footer from "@/components/ui/Footer";

const ptSerif = PT_Serif({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ibrahim - MERN Dev, Meta ads Expert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ptSerif.className} antialiased`}>
        <div className="flex bg-primary text-secondary flex-col min-h-screen mx-auto">
          {/* Sticky Navbar */}
          <header className="sticky top-0 z-50">
            <Navbar />
          </header>
          <main className="flex-grow">{children}</main>
          {/* Footer at the bottom */}
          <footer className="mt-auto">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
